/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	ratelimitsoloiov1alpha1 "github.com/solo-io/gloo-gateway/v2/external/ratelimit.solo.io/v1alpha1"
	scheme "github.com/solo-io/gloo-gateway/v2/internal/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RateLimitConfigsGetter has a method to return a RateLimitConfigInterface.
// A group's client should implement this interface.
type RateLimitConfigsGetter interface {
	RateLimitConfigs(namespace string) RateLimitConfigInterface
}

// RateLimitConfigInterface has methods to work with RateLimitConfig resources.
type RateLimitConfigInterface interface {
	Create(ctx context.Context, rateLimitConfig *ratelimitsoloiov1alpha1.RateLimitConfig, opts v1.CreateOptions) (*ratelimitsoloiov1alpha1.RateLimitConfig, error)
	Update(ctx context.Context, rateLimitConfig *ratelimitsoloiov1alpha1.RateLimitConfig, opts v1.UpdateOptions) (*ratelimitsoloiov1alpha1.RateLimitConfig, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, rateLimitConfig *ratelimitsoloiov1alpha1.RateLimitConfig, opts v1.UpdateOptions) (*ratelimitsoloiov1alpha1.RateLimitConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ratelimitsoloiov1alpha1.RateLimitConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*ratelimitsoloiov1alpha1.RateLimitConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ratelimitsoloiov1alpha1.RateLimitConfig, err error)
	RateLimitConfigExpansion
}

// rateLimitConfigs implements RateLimitConfigInterface
type rateLimitConfigs struct {
	*gentype.ClientWithList[*ratelimitsoloiov1alpha1.RateLimitConfig, *ratelimitsoloiov1alpha1.RateLimitConfigList]
}

// newRateLimitConfigs returns a RateLimitConfigs
func newRateLimitConfigs(c *RatelimitV1alpha1Client, namespace string) *rateLimitConfigs {
	return &rateLimitConfigs{
		gentype.NewClientWithList[*ratelimitsoloiov1alpha1.RateLimitConfig, *ratelimitsoloiov1alpha1.RateLimitConfigList](
			"ratelimitconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *ratelimitsoloiov1alpha1.RateLimitConfig { return &ratelimitsoloiov1alpha1.RateLimitConfig{} },
			func() *ratelimitsoloiov1alpha1.RateLimitConfigList {
				return &ratelimitsoloiov1alpha1.RateLimitConfigList{}
			},
		),
	}
}
