//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package shared

import (
	"sigs.k8s.io/gateway-api/apis/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthConfigRef) DeepCopyInto(out *AuthConfigRef) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(v1.Namespace)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthConfigRef.
func (in *AuthConfigRef) DeepCopy() *AuthConfigRef {
	if in == nil {
		return nil
	}
	out := new(AuthConfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateLimitConfigRef) DeepCopyInto(out *RateLimitConfigRef) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(v1.Namespace)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateLimitConfigRef.
func (in *RateLimitConfigRef) DeepCopy() *RateLimitConfigRef {
	if in == nil {
		return nil
	}
	out := new(RateLimitConfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WAFPolicyRef) DeepCopyInto(out *WAFPolicyRef) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(v1.Namespace)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WAFPolicyRef.
func (in *WAFPolicyRef) DeepCopy() *WAFPolicyRef {
	if in == nil {
		return nil
	}
	out := new(WAFPolicyRef)
	in.DeepCopyInto(out)
	return out
}
