/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	extauthsoloiov1 "github.com/solo-io/kgateway-client/v2/external/extauth.solo.io/v1"
	scheme "github.com/solo-io/kgateway-client/v2/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AuthConfigsGetter has a method to return a AuthConfigInterface.
// A group's client should implement this interface.
type AuthConfigsGetter interface {
	AuthConfigs(namespace string) AuthConfigInterface
}

// AuthConfigInterface has methods to work with AuthConfig resources.
type AuthConfigInterface interface {
	Create(ctx context.Context, authConfig *extauthsoloiov1.AuthConfig, opts metav1.CreateOptions) (*extauthsoloiov1.AuthConfig, error)
	Update(ctx context.Context, authConfig *extauthsoloiov1.AuthConfig, opts metav1.UpdateOptions) (*extauthsoloiov1.AuthConfig, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, authConfig *extauthsoloiov1.AuthConfig, opts metav1.UpdateOptions) (*extauthsoloiov1.AuthConfig, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*extauthsoloiov1.AuthConfig, error)
	List(ctx context.Context, opts metav1.ListOptions) (*extauthsoloiov1.AuthConfigList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *extauthsoloiov1.AuthConfig, err error)
	AuthConfigExpansion
}

// authConfigs implements AuthConfigInterface
type authConfigs struct {
	*gentype.ClientWithList[*extauthsoloiov1.AuthConfig, *extauthsoloiov1.AuthConfigList]
}

// newAuthConfigs returns a AuthConfigs
func newAuthConfigs(c *ExtauthV1Client, namespace string) *authConfigs {
	return &authConfigs{
		gentype.NewClientWithList[*extauthsoloiov1.AuthConfig, *extauthsoloiov1.AuthConfigList](
			"authconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *extauthsoloiov1.AuthConfig { return &extauthsoloiov1.AuthConfig{} },
			func() *extauthsoloiov1.AuthConfigList { return &extauthsoloiov1.AuthConfigList{} },
		),
	}
}
