//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package enterprisekgateway

import (
	"github.com/kgateway-dev/kgateway/v2/api/v1alpha1/kgateway"
	"github.com/kgateway-dev/kgateway/v2/api/v1alpha1/shared"
	v1alpha1shared "github.com/solo-io/kgateway-client/api/v1alpha1/shared"
	appsv1 "k8s.io/api/apps/v1"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apisv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSLambdaTransformation) DeepCopyInto(out *AWSLambdaTransformation) {
	*out = *in
	if in.RequestFormat != nil {
		in, out := &in.RequestFormat, &out.RequestFormat
		*out = new(AWSLambdaTransformFormat)
		**out = **in
	}
	if in.ResponseFormat != nil {
		in, out := &in.ResponseFormat, &out.ResponseFormat
		*out = new(AWSLambdaTransformFormat)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSLambdaTransformation.
func (in *AWSLambdaTransformation) DeepCopy() *AWSLambdaTransformation {
	if in == nil {
		return nil
	}
	out := new(AWSLambdaTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BodyTransformation) DeepCopyInto(out *BodyTransformation) {
	*out = *in
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(InjaTemplate)
		**out = **in
	}
	if in.MergeJsonKeys != nil {
		in, out := &in.MergeJsonKeys, &out.MergeJsonKeys
		*out = make(map[string]OverridableTemplate, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BodyTransformation.
func (in *BodyTransformation) DeepCopy() *BodyTransformation {
	if in == nil {
		return nil
	}
	out := new(BodyTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClaimToHeader) DeepCopyInto(out *ClaimToHeader) {
	*out = *in
	if in.Append != nil {
		in, out := &in.Append, &out.Append
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClaimToHeader.
func (in *ClaimToHeader) DeepCopy() *ClaimToHeader {
	if in == nil {
		return nil
	}
	out := new(ClaimToHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerConfiguration) DeepCopyInto(out *ContainerConfiguration) {
	*out = *in
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(kgateway.Image)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerConfiguration.
func (in *ContainerConfiguration) DeepCopy() *ContainerConfiguration {
	if in == nil {
		return nil
	}
	out := new(ContainerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentConfiguration) DeepCopyInto(out *DeploymentConfiguration) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(kgateway.Pod)
		(*in).DeepCopyInto(*out)
	}
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(ContainerConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Strategy != nil {
		in, out := &in.Strategy, &out.Strategy
		*out = new(appsv1.DeploymentStrategy)
		(*in).DeepCopyInto(*out)
	}
	if in.DeploymentOverlay != nil {
		in, out := &in.DeploymentOverlay, &out.DeploymentOverlay
		*out = new(shared.KubernetesResourceOverlay)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceOverlay != nil {
		in, out := &in.ServiceOverlay, &out.ServiceOverlay
		*out = new(shared.KubernetesResourceOverlay)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceAccountOverlay != nil {
		in, out := &in.ServiceAccountOverlay, &out.ServiceAccountOverlay
		*out = new(shared.KubernetesResourceOverlay)
		(*in).DeepCopyInto(*out)
	}
	if in.PodDisruptionBudget != nil {
		in, out := &in.PodDisruptionBudget, &out.PodDisruptionBudget
		*out = new(shared.KubernetesResourceOverlay)
		(*in).DeepCopyInto(*out)
	}
	if in.HorizontalPodAutoscaler != nil {
		in, out := &in.HorizontalPodAutoscaler, &out.HorizontalPodAutoscaler
		*out = new(shared.KubernetesResourceOverlay)
		(*in).DeepCopyInto(*out)
	}
	if in.VerticalPodAutoscaler != nil {
		in, out := &in.VerticalPodAutoscaler, &out.VerticalPodAutoscaler
		*out = new(shared.KubernetesResourceOverlay)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentConfiguration.
func (in *DeploymentConfiguration) DeepCopy() *DeploymentConfiguration {
	if in == nil {
		return nil
	}
	out := new(DeploymentConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicMetadataValue) DeepCopyInto(out *DynamicMetadataValue) {
	*out = *in
	if in.MetadataNamespace != nil {
		in, out := &in.MetadataNamespace, &out.MetadataNamespace
		*out = new(string)
		**out = **in
	}
	if in.JsonToProto != nil {
		in, out := &in.JsonToProto, &out.JsonToProto
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicMetadataValue.
func (in *DynamicMetadataValue) DeepCopy() *DynamicMetadataValue {
	if in == nil {
		return nil
	}
	out := new(DynamicMetadataValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntExtAuth) DeepCopyInto(out *EntExtAuth) {
	*out = *in
	if in.AuthConfigRef != nil {
		in, out := &in.AuthConfigRef, &out.AuthConfigRef
		*out = new(v1alpha1shared.AuthConfigRef)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtensionRef != nil {
		in, out := &in.ExtensionRef, &out.ExtensionRef
		*out = new(shared.NamespacedObjectReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(shared.PolicyDisable)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntExtAuth.
func (in *EntExtAuth) DeepCopy() *EntExtAuth {
	if in == nil {
		return nil
	}
	out := new(EntExtAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntJWT) DeepCopyInto(out *EntJWT) {
	*out = *in
	if in.Providers != nil {
		in, out := &in.Providers, &out.Providers
		*out = make(map[string]JWTProvider, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.ValidationPolicy != nil {
		in, out := &in.ValidationPolicy, &out.ValidationPolicy
		*out = new(JwtValidationPolicy)
		**out = **in
	}
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(shared.PolicyDisable)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntJWT.
func (in *EntJWT) DeepCopy() *EntJWT {
	if in == nil {
		return nil
	}
	out := new(EntJWT)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntRBAC) DeepCopyInto(out *EntRBAC) {
	*out = *in
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(shared.PolicyDisable)
		**out = **in
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make(map[string]RBACPolicy, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntRBAC.
func (in *EntRBAC) DeepCopy() *EntRBAC {
	if in == nil {
		return nil
	}
	out := new(EntRBAC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntRateLimit) DeepCopyInto(out *EntRateLimit) {
	*out = *in
	in.Global.DeepCopyInto(&out.Global)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntRateLimit.
func (in *EntRateLimit) DeepCopy() *EntRateLimit {
	if in == nil {
		return nil
	}
	out := new(EntRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntTransformation) DeepCopyInto(out *EntTransformation) {
	*out = *in
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = new(StagedTransformations)
		(*in).DeepCopyInto(*out)
	}
	if in.AWSLambda != nil {
		in, out := &in.AWSLambda, &out.AWSLambda
		*out = new(AWSLambdaTransformation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntTransformation.
func (in *EntTransformation) DeepCopy() *EntTransformation {
	if in == nil {
		return nil
	}
	out := new(EntTransformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntWAF) DeepCopyInto(out *EntWAF) {
	*out = *in
	if in.WAFPolicyRef != nil {
		in, out := &in.WAFPolicyRef, &out.WAFPolicyRef
		*out = new(v1alpha1shared.WAFPolicyRef)
		(*in).DeepCopyInto(*out)
	}
	if in.WAFServer != nil {
		in, out := &in.WAFServer, &out.WAFServer
		*out = new(apisv1.BackendObjectReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Disable != nil {
		in, out := &in.Disable, &out.Disable
		*out = new(shared.PolicyDisable)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntWAF.
func (in *EntWAF) DeepCopy() *EntWAF {
	if in == nil {
		return nil
	}
	out := new(EntWAF)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseKgatewayKubernetesProxyConfig) DeepCopyInto(out *EnterpriseKgatewayKubernetesProxyConfig) {
	*out = *in
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(kgateway.ProxyDeployment)
		(*in).DeepCopyInto(*out)
	}
	if in.EnvoyContainer != nil {
		in, out := &in.EnvoyContainer, &out.EnvoyContainer
		*out = new(kgateway.EnvoyContainer)
		(*in).DeepCopyInto(*out)
	}
	if in.SdsContainer != nil {
		in, out := &in.SdsContainer, &out.SdsContainer
		*out = new(kgateway.SdsContainer)
		(*in).DeepCopyInto(*out)
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = new(kgateway.Pod)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(kgateway.Service)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(kgateway.ServiceAccount)
		(*in).DeepCopyInto(*out)
	}
	if in.Istio != nil {
		in, out := &in.Istio, &out.Istio
		*out = new(kgateway.IstioIntegration)
		(*in).DeepCopyInto(*out)
	}
	if in.Stats != nil {
		in, out := &in.Stats, &out.Stats
		*out = new(kgateway.StatsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OmitDefaultSecurityContext != nil {
		in, out := &in.OmitDefaultSecurityContext, &out.OmitDefaultSecurityContext
		*out = new(bool)
		**out = **in
	}
	in.GatewayParametersOverlays.DeepCopyInto(&out.GatewayParametersOverlays)
	if in.SharedExtensions != nil {
		in, out := &in.SharedExtensions, &out.SharedExtensions
		*out = new(Extensions)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseKgatewayKubernetesProxyConfig.
func (in *EnterpriseKgatewayKubernetesProxyConfig) DeepCopy() *EnterpriseKgatewayKubernetesProxyConfig {
	if in == nil {
		return nil
	}
	out := new(EnterpriseKgatewayKubernetesProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseKgatewayParameters) DeepCopyInto(out *EnterpriseKgatewayParameters) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseKgatewayParameters.
func (in *EnterpriseKgatewayParameters) DeepCopy() *EnterpriseKgatewayParameters {
	if in == nil {
		return nil
	}
	out := new(EnterpriseKgatewayParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnterpriseKgatewayParameters) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseKgatewayParametersList) DeepCopyInto(out *EnterpriseKgatewayParametersList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EnterpriseKgatewayParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseKgatewayParametersList.
func (in *EnterpriseKgatewayParametersList) DeepCopy() *EnterpriseKgatewayParametersList {
	if in == nil {
		return nil
	}
	out := new(EnterpriseKgatewayParametersList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnterpriseKgatewayParametersList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseKgatewayParametersSpec) DeepCopyInto(out *EnterpriseKgatewayParametersSpec) {
	*out = *in
	if in.Kube != nil {
		in, out := &in.Kube, &out.Kube
		*out = new(EnterpriseKgatewayKubernetesProxyConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseKgatewayParametersSpec.
func (in *EnterpriseKgatewayParametersSpec) DeepCopy() *EnterpriseKgatewayParametersSpec {
	if in == nil {
		return nil
	}
	out := new(EnterpriseKgatewayParametersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseKgatewayParametersStatus) DeepCopyInto(out *EnterpriseKgatewayParametersStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseKgatewayParametersStatus.
func (in *EnterpriseKgatewayParametersStatus) DeepCopy() *EnterpriseKgatewayParametersStatus {
	if in == nil {
		return nil
	}
	out := new(EnterpriseKgatewayParametersStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseKgatewayTrafficPolicy) DeepCopyInto(out *EnterpriseKgatewayTrafficPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseKgatewayTrafficPolicy.
func (in *EnterpriseKgatewayTrafficPolicy) DeepCopy() *EnterpriseKgatewayTrafficPolicy {
	if in == nil {
		return nil
	}
	out := new(EnterpriseKgatewayTrafficPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnterpriseKgatewayTrafficPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseKgatewayTrafficPolicyList) DeepCopyInto(out *EnterpriseKgatewayTrafficPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EnterpriseKgatewayTrafficPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseKgatewayTrafficPolicyList.
func (in *EnterpriseKgatewayTrafficPolicyList) DeepCopy() *EnterpriseKgatewayTrafficPolicyList {
	if in == nil {
		return nil
	}
	out := new(EnterpriseKgatewayTrafficPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnterpriseKgatewayTrafficPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseKgatewayTrafficPolicySpec) DeepCopyInto(out *EnterpriseKgatewayTrafficPolicySpec) {
	*out = *in
	in.TrafficPolicySpec.DeepCopyInto(&out.TrafficPolicySpec)
	if in.EntRateLimit != nil {
		in, out := &in.EntRateLimit, &out.EntRateLimit
		*out = new(EntRateLimit)
		(*in).DeepCopyInto(*out)
	}
	if in.EntExtAuth != nil {
		in, out := &in.EntExtAuth, &out.EntExtAuth
		*out = new(EntExtAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.EntTransformation != nil {
		in, out := &in.EntTransformation, &out.EntTransformation
		*out = new(EntTransformation)
		(*in).DeepCopyInto(*out)
	}
	if in.EntJWT != nil {
		in, out := &in.EntJWT, &out.EntJWT
		*out = new(StagedJWT)
		(*in).DeepCopyInto(*out)
	}
	if in.EntRBAC != nil {
		in, out := &in.EntRBAC, &out.EntRBAC
		*out = new(EntRBAC)
		(*in).DeepCopyInto(*out)
	}
	if in.EntWAF != nil {
		in, out := &in.EntWAF, &out.EntWAF
		*out = new(EntWAF)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseKgatewayTrafficPolicySpec.
func (in *EnterpriseKgatewayTrafficPolicySpec) DeepCopy() *EnterpriseKgatewayTrafficPolicySpec {
	if in == nil {
		return nil
	}
	out := new(EnterpriseKgatewayTrafficPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Extensions) DeepCopyInto(out *Extensions) {
	*out = *in
	if in.ExtAuth != nil {
		in, out := &in.ExtAuth, &out.ExtAuth
		*out = new(DeploymentConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.RateLimiter != nil {
		in, out := &in.RateLimiter, &out.RateLimiter
		*out = new(DeploymentConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtCache != nil {
		in, out := &in.ExtCache, &out.ExtCache
		*out = new(DeploymentConfiguration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Extensions.
func (in *Extensions) DeepCopy() *Extensions {
	if in == nil {
		return nil
	}
	out := new(Extensions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Extraction) DeepCopyInto(out *Extraction) {
	*out = *in
	if in.ExtractionBody != nil {
		in, out := &in.ExtractionBody, &out.ExtractionBody
		*out = new(bool)
		**out = **in
	}
	if in.ExtractionHeader != nil {
		in, out := &in.ExtractionHeader, &out.ExtractionHeader
		*out = new(string)
		**out = **in
	}
	if in.Subgroup != nil {
		in, out := &in.Subgroup, &out.Subgroup
		*out = new(int32)
		**out = **in
	}
	if in.ReplacementText != nil {
		in, out := &in.ReplacementText, &out.ReplacementText
		*out = new(string)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(TransformationExtractMode)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Extraction.
func (in *Extraction) DeepCopy() *Extraction {
	if in == nil {
		return nil
	}
	out := new(Extraction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalRateLimit) DeepCopyInto(out *GlobalRateLimit) {
	*out = *in
	if in.ExtensionRef != nil {
		in, out := &in.ExtensionRef, &out.ExtensionRef
		*out = new(shared.NamespacedObjectReference)
		(*in).DeepCopyInto(*out)
	}
	if in.RateLimitConfigRefs != nil {
		in, out := &in.RateLimitConfigRefs, &out.RateLimitConfigRefs
		*out = make([]v1alpha1shared.RateLimitConfigRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalRateLimit.
func (in *GlobalRateLimit) DeepCopy() *GlobalRateLimit {
	if in == nil {
		return nil
	}
	out := new(GlobalRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderBodyTransform) DeepCopyInto(out *HeaderBodyTransform) {
	*out = *in
	if in.AddRequestMetadata != nil {
		in, out := &in.AddRequestMetadata, &out.AddRequestMetadata
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderBodyTransform.
func (in *HeaderBodyTransform) DeepCopy() *HeaderBodyTransform {
	if in == nil {
		return nil
	}
	out := new(HeaderBodyTransform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderToAppend) DeepCopyInto(out *HeaderToAppend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderToAppend.
func (in *HeaderToAppend) DeepCopy() *HeaderToAppend {
	if in == nil {
		return nil
	}
	out := new(HeaderToAppend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWKS) DeepCopyInto(out *JWKS) {
	*out = *in
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(LocalJWKS)
		**out = **in
	}
	if in.Remote != nil {
		in, out := &in.Remote, &out.Remote
		*out = new(RemoteJWKS)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWKS.
func (in *JWKS) DeepCopy() *JWKS {
	if in == nil {
		return nil
	}
	out := new(JWKS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JWTProvider) DeepCopyInto(out *JWTProvider) {
	*out = *in
	in.JWKS.DeepCopyInto(&out.JWKS)
	if in.Audiences != nil {
		in, out := &in.Audiences, &out.Audiences
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Issuer != nil {
		in, out := &in.Issuer, &out.Issuer
		*out = new(string)
		**out = **in
	}
	if in.TokenSource != nil {
		in, out := &in.TokenSource, &out.TokenSource
		*out = new(TokenSource)
		(*in).DeepCopyInto(*out)
	}
	if in.KeepToken != nil {
		in, out := &in.KeepToken, &out.KeepToken
		*out = new(bool)
		**out = **in
	}
	if in.ClaimsToHeaders != nil {
		in, out := &in.ClaimsToHeaders, &out.ClaimsToHeaders
		*out = make([]ClaimToHeader, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ClockSkewSeconds != nil {
		in, out := &in.ClockSkewSeconds, &out.ClockSkewSeconds
		*out = new(int32)
		**out = **in
	}
	if in.AttachFailedStatusToMetadata != nil {
		in, out := &in.AttachFailedStatusToMetadata, &out.AttachFailedStatusToMetadata
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JWTProvider.
func (in *JWTProvider) DeepCopy() *JWTProvider {
	if in == nil {
		return nil
	}
	out := new(JWTProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JwksAsyncFetch) DeepCopyInto(out *JwksAsyncFetch) {
	*out = *in
	if in.FastListener != nil {
		in, out := &in.FastListener, &out.FastListener
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JwksAsyncFetch.
func (in *JwksAsyncFetch) DeepCopy() *JwksAsyncFetch {
	if in == nil {
		return nil
	}
	out := new(JwksAsyncFetch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalJWKS) DeepCopyInto(out *LocalJWKS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalJWKS.
func (in *LocalJWKS) DeepCopy() *LocalJWKS {
	if in == nil {
		return nil
	}
	out := new(LocalJWKS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OverridableTemplate) DeepCopyInto(out *OverridableTemplate) {
	*out = *in
	if in.OverrideEmpty != nil {
		in, out := &in.OverrideEmpty, &out.OverrideEmpty
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OverridableTemplate.
func (in *OverridableTemplate) DeepCopy() *OverridableTemplate {
	if in == nil {
		return nil
	}
	out := new(OverridableTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryParameterMatcher) DeepCopyInto(out *QueryParameterMatcher) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.Regex != nil {
		in, out := &in.Regex, &out.Regex
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryParameterMatcher.
func (in *QueryParameterMatcher) DeepCopy() *QueryParameterMatcher {
	if in == nil {
		return nil
	}
	out := new(QueryParameterMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACJWTPrincipal) DeepCopyInto(out *RBACJWTPrincipal) {
	*out = *in
	if in.Claims != nil {
		in, out := &in.Claims, &out.Claims
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Provider != nil {
		in, out := &in.Provider, &out.Provider
		*out = new(string)
		**out = **in
	}
	if in.Matcher != nil {
		in, out := &in.Matcher, &out.Matcher
		*out = new(RBACJWTPrincipalClaimMatcher)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACJWTPrincipal.
func (in *RBACJWTPrincipal) DeepCopy() *RBACJWTPrincipal {
	if in == nil {
		return nil
	}
	out := new(RBACJWTPrincipal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACPermissions) DeepCopyInto(out *RBACPermissions) {
	*out = *in
	if in.PathPrefix != nil {
		in, out := &in.PathPrefix, &out.PathPrefix
		*out = new(string)
		**out = **in
	}
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACPermissions.
func (in *RBACPermissions) DeepCopy() *RBACPermissions {
	if in == nil {
		return nil
	}
	out := new(RBACPermissions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACPolicy) DeepCopyInto(out *RBACPolicy) {
	*out = *in
	if in.Principals != nil {
		in, out := &in.Principals, &out.Principals
		*out = make([]RBACPrincipal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = new(RBACPermissions)
		(*in).DeepCopyInto(*out)
	}
	if in.NestedClaimDelimiter != nil {
		in, out := &in.NestedClaimDelimiter, &out.NestedClaimDelimiter
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACPolicy.
func (in *RBACPolicy) DeepCopy() *RBACPolicy {
	if in == nil {
		return nil
	}
	out := new(RBACPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBACPrincipal) DeepCopyInto(out *RBACPrincipal) {
	*out = *in
	in.JWTPrincipal.DeepCopyInto(&out.JWTPrincipal)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBACPrincipal.
func (in *RBACPrincipal) DeepCopy() *RBACPrincipal {
	if in == nil {
		return nil
	}
	out := new(RBACPrincipal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RangeMatch) DeepCopyInto(out *RangeMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RangeMatch.
func (in *RangeMatch) DeepCopy() *RangeMatch {
	if in == nil {
		return nil
	}
	out := new(RangeMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegexMatcher) DeepCopyInto(out *RegexMatcher) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegexMatcher.
func (in *RegexMatcher) DeepCopy() *RegexMatcher {
	if in == nil {
		return nil
	}
	out := new(RegexMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemoteJWKS) DeepCopyInto(out *RemoteJWKS) {
	*out = *in
	in.BackendRef.DeepCopyInto(&out.BackendRef)
	if in.CacheDuration != nil {
		in, out := &in.CacheDuration, &out.CacheDuration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.AsyncFetch != nil {
		in, out := &in.AsyncFetch, &out.AsyncFetch
		*out = new(JwksAsyncFetch)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemoteJWKS.
func (in *RemoteJWKS) DeepCopy() *RemoteJWKS {
	if in == nil {
		return nil
	}
	out := new(RemoteJWKS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestMatcher) DeepCopyInto(out *RequestMatcher) {
	*out = *in
	if in.Matcher != nil {
		in, out := &in.Matcher, &out.Matcher
		*out = new(TransformationRequestMatcher)
		(*in).DeepCopyInto(*out)
	}
	if in.ClearRouteCache != nil {
		in, out := &in.ClearRouteCache, &out.ClearRouteCache
		*out = new(bool)
		**out = **in
	}
	in.Transformation.DeepCopyInto(&out.Transformation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestMatcher.
func (in *RequestMatcher) DeepCopy() *RequestMatcher {
	if in == nil {
		return nil
	}
	out := new(RequestMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestResponseTransformations) DeepCopyInto(out *RequestResponseTransformations) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make([]RequestMatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Responses != nil {
		in, out := &in.Responses, &out.Responses
		*out = make([]ResponseMatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestResponseTransformations.
func (in *RequestResponseTransformations) DeepCopy() *RequestResponseTransformations {
	if in == nil {
		return nil
	}
	out := new(RequestResponseTransformations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResponseMatcher) DeepCopyInto(out *ResponseMatcher) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]TransformationHeaderMatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResponseCodeDetails != nil {
		in, out := &in.ResponseCodeDetails, &out.ResponseCodeDetails
		*out = new(string)
		**out = **in
	}
	in.Transformation.DeepCopyInto(&out.Transformation)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResponseMatcher.
func (in *ResponseMatcher) DeepCopy() *ResponseMatcher {
	if in == nil {
		return nil
	}
	out := new(ResponseMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpanTransformer) DeepCopyInto(out *SpanTransformer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpanTransformer.
func (in *SpanTransformer) DeepCopy() *SpanTransformer {
	if in == nil {
		return nil
	}
	out := new(SpanTransformer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StagedJWT) DeepCopyInto(out *StagedJWT) {
	*out = *in
	if in.AfterExtAuth != nil {
		in, out := &in.AfterExtAuth, &out.AfterExtAuth
		*out = new(EntJWT)
		(*in).DeepCopyInto(*out)
	}
	if in.BeforeExtAuth != nil {
		in, out := &in.BeforeExtAuth, &out.BeforeExtAuth
		*out = new(EntJWT)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StagedJWT.
func (in *StagedJWT) DeepCopy() *StagedJWT {
	if in == nil {
		return nil
	}
	out := new(StagedJWT)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StagedTransformations) DeepCopyInto(out *StagedTransformations) {
	*out = *in
	if in.Early != nil {
		in, out := &in.Early, &out.Early
		*out = new(RequestResponseTransformations)
		(*in).DeepCopyInto(*out)
	}
	if in.Regular != nil {
		in, out := &in.Regular, &out.Regular
		*out = new(RequestResponseTransformations)
		(*in).DeepCopyInto(*out)
	}
	if in.PostRouting != nil {
		in, out := &in.PostRouting, &out.PostRouting
		*out = new(RequestResponseTransformations)
		(*in).DeepCopyInto(*out)
	}
	if in.LogRequestResponseInfo != nil {
		in, out := &in.LogRequestResponseInfo, &out.LogRequestResponseInfo
		*out = new(bool)
		**out = **in
	}
	if in.EscapeCharacters != nil {
		in, out := &in.EscapeCharacters, &out.EscapeCharacters
		*out = new(EscapeCharactersBehavior)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StagedTransformations.
func (in *StagedTransformations) DeepCopy() *StagedTransformations {
	if in == nil {
		return nil
	}
	out := new(StagedTransformations)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StringMatch) DeepCopyInto(out *StringMatch) {
	*out = *in
	if in.Exact != nil {
		in, out := &in.Exact, &out.Exact
		*out = new(string)
		**out = **in
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.Suffix != nil {
		in, out := &in.Suffix, &out.Suffix
		*out = new(string)
		**out = **in
	}
	if in.Regex != nil {
		in, out := &in.Regex, &out.Regex
		*out = new(RegexMatcher)
		**out = **in
	}
	if in.IgnoreCase != nil {
		in, out := &in.IgnoreCase, &out.IgnoreCase
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StringMatch.
func (in *StringMatch) DeepCopy() *StringMatch {
	if in == nil {
		return nil
	}
	out := new(StringMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TlsContextMatchOptions) DeepCopyInto(out *TlsContextMatchOptions) {
	*out = *in
	if in.Presented != nil {
		in, out := &in.Presented, &out.Presented
		*out = new(bool)
		**out = **in
	}
	if in.Validated != nil {
		in, out := &in.Validated, &out.Validated
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TlsContextMatchOptions.
func (in *TlsContextMatchOptions) DeepCopy() *TlsContextMatchOptions {
	if in == nil {
		return nil
	}
	out := new(TlsContextMatchOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenSource) DeepCopyInto(out *TokenSource) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]TokenSourceHeaderSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.QueryParams != nil {
		in, out := &in.QueryParams, &out.QueryParams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenSource.
func (in *TokenSource) DeepCopy() *TokenSource {
	if in == nil {
		return nil
	}
	out := new(TokenSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenSourceHeaderSource) DeepCopyInto(out *TokenSourceHeaderSource) {
	*out = *in
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenSourceHeaderSource.
func (in *TokenSourceHeaderSource) DeepCopy() *TokenSourceHeaderSource {
	if in == nil {
		return nil
	}
	out := new(TokenSourceHeaderSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Transformation) DeepCopyInto(out *Transformation) {
	*out = *in
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(TransformationTemplate)
		(*in).DeepCopyInto(*out)
	}
	if in.HeaderBody != nil {
		in, out := &in.HeaderBody, &out.HeaderBody
		*out = new(HeaderBodyTransform)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Transformation.
func (in *Transformation) DeepCopy() *Transformation {
	if in == nil {
		return nil
	}
	out := new(Transformation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformationHeaderMatcher) DeepCopyInto(out *TransformationHeaderMatcher) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.Regex != nil {
		in, out := &in.Regex, &out.Regex
		*out = new(bool)
		**out = **in
	}
	if in.InvertMatch != nil {
		in, out := &in.InvertMatch, &out.InvertMatch
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformationHeaderMatcher.
func (in *TransformationHeaderMatcher) DeepCopy() *TransformationHeaderMatcher {
	if in == nil {
		return nil
	}
	out := new(TransformationHeaderMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformationRequestMatcher) DeepCopyInto(out *TransformationRequestMatcher) {
	*out = *in
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Regex != nil {
		in, out := &in.Regex, &out.Regex
		*out = new(RegexMatcher)
		**out = **in
	}
	if in.Connect != nil {
		in, out := &in.Connect, &out.Connect
		*out = new(bool)
		**out = **in
	}
	if in.CaseSensitive != nil {
		in, out := &in.CaseSensitive, &out.CaseSensitive
		*out = new(bool)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]TransformationHeaderMatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.QueryParameters != nil {
		in, out := &in.QueryParameters, &out.QueryParameters
		*out = make([]QueryParameterMatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Grpc != nil {
		in, out := &in.Grpc, &out.Grpc
		*out = new(bool)
		**out = **in
	}
	if in.TlsContext != nil {
		in, out := &in.TlsContext, &out.TlsContext
		*out = new(TlsContextMatchOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformationRequestMatcher.
func (in *TransformationRequestMatcher) DeepCopy() *TransformationRequestMatcher {
	if in == nil {
		return nil
	}
	out := new(TransformationRequestMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformationTemplate) DeepCopyInto(out *TransformationTemplate) {
	*out = *in
	if in.AdvancedTemplates != nil {
		in, out := &in.AdvancedTemplates, &out.AdvancedTemplates
		*out = new(bool)
		**out = **in
	}
	if in.Extractors != nil {
		in, out := &in.Extractors, &out.Extractors
		*out = make(map[string]Extraction, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]InjaTemplate, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HeadersToAppend != nil {
		in, out := &in.HeadersToAppend, &out.HeadersToAppend
		*out = make([]HeaderToAppend, len(*in))
		copy(*out, *in)
	}
	if in.HeadersToRemove != nil {
		in, out := &in.HeadersToRemove, &out.HeadersToRemove
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BodyTransformation != nil {
		in, out := &in.BodyTransformation, &out.BodyTransformation
		*out = new(BodyTransformation)
		(*in).DeepCopyInto(*out)
	}
	if in.ParseBodyBehavior != nil {
		in, out := &in.ParseBodyBehavior, &out.ParseBodyBehavior
		*out = new(RequestBodyParse)
		**out = **in
	}
	if in.IgnoreErrorOnParse != nil {
		in, out := &in.IgnoreErrorOnParse, &out.IgnoreErrorOnParse
		*out = new(bool)
		**out = **in
	}
	if in.DynamicMetadataValues != nil {
		in, out := &in.DynamicMetadataValues, &out.DynamicMetadataValues
		*out = make([]DynamicMetadataValue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EscapeCharacters != nil {
		in, out := &in.EscapeCharacters, &out.EscapeCharacters
		*out = new(EscapeCharactersBehavior)
		**out = **in
	}
	if in.SpanTransformer != nil {
		in, out := &in.SpanTransformer, &out.SpanTransformer
		*out = new(SpanTransformer)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformationTemplate.
func (in *TransformationTemplate) DeepCopy() *TransformationTemplate {
	if in == nil {
		return nil
	}
	out := new(TransformationTemplate)
	in.DeepCopyInto(out)
	return out
}
