//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package waf

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apisv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapRef) DeepCopyInto(out *ConfigMapRef) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapRef.
func (in *ConfigMapRef) DeepCopy() *ConfigMapRef {
	if in == nil {
		return nil
	}
	out := new(ConfigMapRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreRuleSet) DeepCopyInto(out *CoreRuleSet) {
	*out = *in
	in.Settings.DeepCopyInto(&out.Settings)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreRuleSet.
func (in *CoreRuleSet) DeepCopy() *CoreRuleSet {
	if in == nil {
		return nil
	}
	out := new(CoreRuleSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomInterventionResponse) DeepCopyInto(out *CustomInterventionResponse) {
	*out = *in
	if in.StatusCode != nil {
		in, out := &in.StatusCode, &out.StatusCode
		*out = new(int32)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = new(CustomInterventionResponseHeaders)
		(*in).DeepCopyInto(*out)
	}
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomInterventionResponse.
func (in *CustomInterventionResponse) DeepCopy() *CustomInterventionResponse {
	if in == nil {
		return nil
	}
	out := new(CustomInterventionResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomInterventionResponseHeader) DeepCopyInto(out *CustomInterventionResponseHeader) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomInterventionResponseHeader.
func (in *CustomInterventionResponseHeader) DeepCopy() *CustomInterventionResponseHeader {
	if in == nil {
		return nil
	}
	out := new(CustomInterventionResponseHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomInterventionResponseHeaders) DeepCopyInto(out *CustomInterventionResponseHeaders) {
	*out = *in
	if in.SetHeaders != nil {
		in, out := &in.SetHeaders, &out.SetHeaders
		*out = make([]CustomInterventionResponseHeader, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomInterventionResponseHeaders.
func (in *CustomInterventionResponseHeaders) DeepCopy() *CustomInterventionResponseHeaders {
	if in == nil {
		return nil
	}
	out := new(CustomInterventionResponseHeaders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DirectiveSource) DeepCopyInto(out *DirectiveSource) {
	*out = *in
	if in.Inline != nil {
		in, out := &in.Inline, &out.Inline
		*out = new(string)
		**out = **in
	}
	if in.ConfigMap != nil {
		in, out := &in.ConfigMap, &out.ConfigMap
		*out = new(ConfigMapRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DirectiveSource.
func (in *DirectiveSource) DeepCopy() *DirectiveSource {
	if in == nil {
		return nil
	}
	out := new(DirectiveSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WAFPolicy) DeepCopyInto(out *WAFPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WAFPolicy.
func (in *WAFPolicy) DeepCopy() *WAFPolicy {
	if in == nil {
		return nil
	}
	out := new(WAFPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WAFPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WAFPolicyList) DeepCopyInto(out *WAFPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WAFPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WAFPolicyList.
func (in *WAFPolicyList) DeepCopy() *WAFPolicyList {
	if in == nil {
		return nil
	}
	out := new(WAFPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WAFPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WAFPolicySpec) DeepCopyInto(out *WAFPolicySpec) {
	*out = *in
	if in.CoreRuleSet != nil {
		in, out := &in.CoreRuleSet, &out.CoreRuleSet
		*out = new(CoreRuleSet)
		(*in).DeepCopyInto(*out)
	}
	in.RuleEngineSettings.DeepCopyInto(&out.RuleEngineSettings)
	if in.CustomDirectives != nil {
		in, out := &in.CustomDirectives, &out.CustomDirectives
		*out = make([]DirectiveSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomInterventionResponse != nil {
		in, out := &in.CustomInterventionResponse, &out.CustomInterventionResponse
		*out = new(CustomInterventionResponse)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WAFPolicySpec.
func (in *WAFPolicySpec) DeepCopy() *WAFPolicySpec {
	if in == nil {
		return nil
	}
	out := new(WAFPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WAFPolicyStatus) DeepCopyInto(out *WAFPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Ancestors != nil {
		in, out := &in.Ancestors, &out.Ancestors
		*out = make([]apisv1.PolicyAncestorStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WAFPolicyStatus.
func (in *WAFPolicyStatus) DeepCopy() *WAFPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(WAFPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
