/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package portal

import (
	context "context"

	v1alpha1portal "github.com/solo-io/kgateway-client/v2/api/v1alpha1/portal"
	scheme "github.com/solo-io/kgateway-client/v2/portal/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ApiDocsGetter has a method to return a ApiDocInterface.
// A group's client should implement this interface.
type ApiDocsGetter interface {
	ApiDocs(namespace string) ApiDocInterface
}

// ApiDocInterface has methods to work with ApiDoc resources.
type ApiDocInterface interface {
	Create(ctx context.Context, apiDoc *v1alpha1portal.ApiDoc, opts v1.CreateOptions) (*v1alpha1portal.ApiDoc, error)
	Update(ctx context.Context, apiDoc *v1alpha1portal.ApiDoc, opts v1.UpdateOptions) (*v1alpha1portal.ApiDoc, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, apiDoc *v1alpha1portal.ApiDoc, opts v1.UpdateOptions) (*v1alpha1portal.ApiDoc, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1portal.ApiDoc, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1portal.ApiDocList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1portal.ApiDoc, err error)
	ApiDocExpansion
}

// apiDocs implements ApiDocInterface
type apiDocs struct {
	*gentype.ClientWithList[*v1alpha1portal.ApiDoc, *v1alpha1portal.ApiDocList]
}

// newApiDocs returns a ApiDocs
func newApiDocs(c *PortalPortalClient, namespace string) *apiDocs {
	return &apiDocs{
		gentype.NewClientWithList[*v1alpha1portal.ApiDoc, *v1alpha1portal.ApiDocList](
			"apidocs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1portal.ApiDoc { return &v1alpha1portal.ApiDoc{} },
			func() *v1alpha1portal.ApiDocList { return &v1alpha1portal.ApiDocList{} },
		),
	}
}
