/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package portal

import (
	context "context"

	v1alpha1portal "github.com/solo-io/kgateway-client/v2/api/v1alpha1/portal"
	scheme "github.com/solo-io/kgateway-client/v2/portal/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PortalsGetter has a method to return a PortalInterface.
// A group's client should implement this interface.
type PortalsGetter interface {
	Portals(namespace string) PortalInterface
}

// PortalInterface has methods to work with Portal resources.
type PortalInterface interface {
	Create(ctx context.Context, portal *v1alpha1portal.Portal, opts v1.CreateOptions) (*v1alpha1portal.Portal, error)
	Update(ctx context.Context, portal *v1alpha1portal.Portal, opts v1.UpdateOptions) (*v1alpha1portal.Portal, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, portal *v1alpha1portal.Portal, opts v1.UpdateOptions) (*v1alpha1portal.Portal, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1portal.Portal, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1portal.PortalList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1portal.Portal, err error)
	PortalExpansion
}

// portals implements PortalInterface
type portals struct {
	*gentype.ClientWithList[*v1alpha1portal.Portal, *v1alpha1portal.PortalList]
}

// newPortals returns a Portals
func newPortals(c *PortalPortalClient, namespace string) *portals {
	return &portals{
		gentype.NewClientWithList[*v1alpha1portal.Portal, *v1alpha1portal.PortalList](
			"portals",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1portal.Portal { return &v1alpha1portal.Portal{} },
			func() *v1alpha1portal.PortalList { return &v1alpha1portal.PortalList{} },
		),
	}
}
