/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package portal

import (
	context "context"

	v1alpha1portal "github.com/solo-io/kgateway-client/v2/api/v1alpha1/portal"
	scheme "github.com/solo-io/kgateway-client/v2/portal/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VisibilityPoliciesGetter has a method to return a VisibilityPolicyInterface.
// A group's client should implement this interface.
type VisibilityPoliciesGetter interface {
	VisibilityPolicies(namespace string) VisibilityPolicyInterface
}

// VisibilityPolicyInterface has methods to work with VisibilityPolicy resources.
type VisibilityPolicyInterface interface {
	Create(ctx context.Context, visibilityPolicy *v1alpha1portal.VisibilityPolicy, opts v1.CreateOptions) (*v1alpha1portal.VisibilityPolicy, error)
	Update(ctx context.Context, visibilityPolicy *v1alpha1portal.VisibilityPolicy, opts v1.UpdateOptions) (*v1alpha1portal.VisibilityPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1portal.VisibilityPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1portal.VisibilityPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1portal.VisibilityPolicy, err error)
	VisibilityPolicyExpansion
}

// visibilityPolicies implements VisibilityPolicyInterface
type visibilityPolicies struct {
	*gentype.ClientWithList[*v1alpha1portal.VisibilityPolicy, *v1alpha1portal.VisibilityPolicyList]
}

// newVisibilityPolicies returns a VisibilityPolicies
func newVisibilityPolicies(c *PortalPortalClient, namespace string) *visibilityPolicies {
	return &visibilityPolicies{
		gentype.NewClientWithList[*v1alpha1portal.VisibilityPolicy, *v1alpha1portal.VisibilityPolicyList](
			"visibilitypolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1portal.VisibilityPolicy { return &v1alpha1portal.VisibilityPolicy{} },
			func() *v1alpha1portal.VisibilityPolicyList { return &v1alpha1portal.VisibilityPolicyList{} },
		),
	}
}
