//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package enterpriseagentgateway

import (
	"github.com/kgateway-dev/kgateway/v2/api/v1alpha1/agentgateway"
	"github.com/kgateway-dev/kgateway/v2/api/v1alpha1/shared"
	v1alpha1shared "github.com/solo-io/kgateway-client/v2/api/v1alpha1/shared"
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apisv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentgatewayExtensions) DeepCopyInto(out *AgentgatewayExtensions) {
	*out = *in
	if in.ExtAuth != nil {
		in, out := &in.ExtAuth, &out.ExtAuth
		*out = new(ExtensionDeployment)
		(*in).DeepCopyInto(*out)
	}
	if in.RateLimiter != nil {
		in, out := &in.RateLimiter, &out.RateLimiter
		*out = new(ExtensionDeployment)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtCache != nil {
		in, out := &in.ExtCache, &out.ExtCache
		*out = new(ExtensionDeployment)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentgatewayExtensions.
func (in *AgentgatewayExtensions) DeepCopy() *AgentgatewayExtensions {
	if in == nil {
		return nil
	}
	out := new(AgentgatewayExtensions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgwGlobalRateLimit) DeepCopyInto(out *AgwGlobalRateLimit) {
	*out = *in
	if in.Domain != nil {
		in, out := &in.Domain, &out.Domain
		*out = new(ShortString)
		**out = **in
	}
	if in.BackendRef != nil {
		in, out := &in.BackendRef, &out.BackendRef
		*out = new(apisv1.BackendObjectReference)
		(*in).DeepCopyInto(*out)
	}
	if in.RateLimitConfigRefs != nil {
		in, out := &in.RateLimitConfigRefs, &out.RateLimitConfigRefs
		*out = make([]v1alpha1shared.RateLimitConfigRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgwGlobalRateLimit.
func (in *AgwGlobalRateLimit) DeepCopy() *AgwGlobalRateLimit {
	if in == nil {
		return nil
	}
	out := new(AgwGlobalRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CA) DeepCopyInto(out *CA) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.TrustDomain != nil {
		in, out := &in.TrustDomain, &out.TrustDomain
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CA.
func (in *CA) DeepCopy() *CA {
	if in == nil {
		return nil
	}
	out := new(CA)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseAgentgatewayExtAuth) DeepCopyInto(out *EnterpriseAgentgatewayExtAuth) {
	*out = *in
	if in.AuthConfigRef != nil {
		in, out := &in.AuthConfigRef, &out.AuthConfigRef
		*out = new(v1alpha1shared.AuthConfigRef)
		(*in).DeepCopyInto(*out)
	}
	if in.BackendRef != nil {
		in, out := &in.BackendRef, &out.BackendRef
		*out = new(apisv1.BackendObjectReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseAgentgatewayExtAuth.
func (in *EnterpriseAgentgatewayExtAuth) DeepCopy() *EnterpriseAgentgatewayExtAuth {
	if in == nil {
		return nil
	}
	out := new(EnterpriseAgentgatewayExtAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseAgentgatewayParameters) DeepCopyInto(out *EnterpriseAgentgatewayParameters) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseAgentgatewayParameters.
func (in *EnterpriseAgentgatewayParameters) DeepCopy() *EnterpriseAgentgatewayParameters {
	if in == nil {
		return nil
	}
	out := new(EnterpriseAgentgatewayParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnterpriseAgentgatewayParameters) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseAgentgatewayParametersList) DeepCopyInto(out *EnterpriseAgentgatewayParametersList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EnterpriseAgentgatewayParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseAgentgatewayParametersList.
func (in *EnterpriseAgentgatewayParametersList) DeepCopy() *EnterpriseAgentgatewayParametersList {
	if in == nil {
		return nil
	}
	out := new(EnterpriseAgentgatewayParametersList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnterpriseAgentgatewayParametersList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseAgentgatewayParametersSpec) DeepCopyInto(out *EnterpriseAgentgatewayParametersSpec) {
	*out = *in
	in.AgentgatewayParametersSpec.DeepCopyInto(&out.AgentgatewayParametersSpec)
	if in.SharedExtensions != nil {
		in, out := &in.SharedExtensions, &out.SharedExtensions
		*out = new(AgentgatewayExtensions)
		(*in).DeepCopyInto(*out)
	}
	if in.CA != nil {
		in, out := &in.CA, &out.CA
		*out = new(CA)
		(*in).DeepCopyInto(*out)
	}
	if in.IstioClusterId != nil {
		in, out := &in.IstioClusterId, &out.IstioClusterId
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseAgentgatewayParametersSpec.
func (in *EnterpriseAgentgatewayParametersSpec) DeepCopy() *EnterpriseAgentgatewayParametersSpec {
	if in == nil {
		return nil
	}
	out := new(EnterpriseAgentgatewayParametersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseAgentgatewayParametersStatus) DeepCopyInto(out *EnterpriseAgentgatewayParametersStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseAgentgatewayParametersStatus.
func (in *EnterpriseAgentgatewayParametersStatus) DeepCopy() *EnterpriseAgentgatewayParametersStatus {
	if in == nil {
		return nil
	}
	out := new(EnterpriseAgentgatewayParametersStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseAgentgatewayPolicy) DeepCopyInto(out *EnterpriseAgentgatewayPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseAgentgatewayPolicy.
func (in *EnterpriseAgentgatewayPolicy) DeepCopy() *EnterpriseAgentgatewayPolicy {
	if in == nil {
		return nil
	}
	out := new(EnterpriseAgentgatewayPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnterpriseAgentgatewayPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseAgentgatewayPolicyBackend) DeepCopyInto(out *EnterpriseAgentgatewayPolicyBackend) {
	*out = *in
	in.BackendSimple.DeepCopyInto(&out.BackendSimple)
	if in.AI != nil {
		in, out := &in.AI, &out.AI
		*out = new(agentgateway.BackendAI)
		(*in).DeepCopyInto(*out)
	}
	if in.MCP != nil {
		in, out := &in.MCP, &out.MCP
		*out = new(agentgateway.BackendMCP)
		(*in).DeepCopyInto(*out)
	}
	if in.TokenExchange != nil {
		in, out := &in.TokenExchange, &out.TokenExchange
		*out = new(TokenExchangeCfg)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseAgentgatewayPolicyBackend.
func (in *EnterpriseAgentgatewayPolicyBackend) DeepCopy() *EnterpriseAgentgatewayPolicyBackend {
	if in == nil {
		return nil
	}
	out := new(EnterpriseAgentgatewayPolicyBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseAgentgatewayPolicyFrontend) DeepCopyInto(out *EnterpriseAgentgatewayPolicyFrontend) {
	*out = *in
	in.Frontend.DeepCopyInto(&out.Frontend)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseAgentgatewayPolicyFrontend.
func (in *EnterpriseAgentgatewayPolicyFrontend) DeepCopy() *EnterpriseAgentgatewayPolicyFrontend {
	if in == nil {
		return nil
	}
	out := new(EnterpriseAgentgatewayPolicyFrontend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseAgentgatewayPolicyList) DeepCopyInto(out *EnterpriseAgentgatewayPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EnterpriseAgentgatewayPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseAgentgatewayPolicyList.
func (in *EnterpriseAgentgatewayPolicyList) DeepCopy() *EnterpriseAgentgatewayPolicyList {
	if in == nil {
		return nil
	}
	out := new(EnterpriseAgentgatewayPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EnterpriseAgentgatewayPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseAgentgatewayPolicySpec) DeepCopyInto(out *EnterpriseAgentgatewayPolicySpec) {
	*out = *in
	if in.TargetRefs != nil {
		in, out := &in.TargetRefs, &out.TargetRefs
		*out = make([]shared.LocalPolicyTargetReferenceWithSectionName, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TargetSelectors != nil {
		in, out := &in.TargetSelectors, &out.TargetSelectors
		*out = make([]shared.LocalPolicyTargetSelectorWithSectionName, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Frontend != nil {
		in, out := &in.Frontend, &out.Frontend
		*out = new(EnterpriseAgentgatewayPolicyFrontend)
		(*in).DeepCopyInto(*out)
	}
	if in.Traffic != nil {
		in, out := &in.Traffic, &out.Traffic
		*out = new(EnterpriseAgentgatewayPolicyTraffic)
		(*in).DeepCopyInto(*out)
	}
	if in.Backend != nil {
		in, out := &in.Backend, &out.Backend
		*out = new(EnterpriseAgentgatewayPolicyBackend)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseAgentgatewayPolicySpec.
func (in *EnterpriseAgentgatewayPolicySpec) DeepCopy() *EnterpriseAgentgatewayPolicySpec {
	if in == nil {
		return nil
	}
	out := new(EnterpriseAgentgatewayPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseAgentgatewayPolicyTraffic) DeepCopyInto(out *EnterpriseAgentgatewayPolicyTraffic) {
	*out = *in
	in.Traffic.DeepCopyInto(&out.Traffic)
	if in.EntRateLimit != nil {
		in, out := &in.EntRateLimit, &out.EntRateLimit
		*out = new(EnterpriseAgentgatewayRateLimit)
		(*in).DeepCopyInto(*out)
	}
	if in.EntExtAuth != nil {
		in, out := &in.EntExtAuth, &out.EntExtAuth
		*out = new(EnterpriseAgentgatewayExtAuth)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseAgentgatewayPolicyTraffic.
func (in *EnterpriseAgentgatewayPolicyTraffic) DeepCopy() *EnterpriseAgentgatewayPolicyTraffic {
	if in == nil {
		return nil
	}
	out := new(EnterpriseAgentgatewayPolicyTraffic)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseAgentgatewayRateLimit) DeepCopyInto(out *EnterpriseAgentgatewayRateLimit) {
	*out = *in
	in.Global.DeepCopyInto(&out.Global)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseAgentgatewayRateLimit.
func (in *EnterpriseAgentgatewayRateLimit) DeepCopy() *EnterpriseAgentgatewayRateLimit {
	if in == nil {
		return nil
	}
	out := new(EnterpriseAgentgatewayRateLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionDeployment) DeepCopyInto(out *ExtensionDeployment) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(agentgateway.Image)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(shared.KubernetesResourceOverlay)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(shared.KubernetesResourceOverlay)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(shared.KubernetesResourceOverlay)
		(*in).DeepCopyInto(*out)
	}
	if in.PodDisruptionBudget != nil {
		in, out := &in.PodDisruptionBudget, &out.PodDisruptionBudget
		*out = new(shared.KubernetesResourceOverlay)
		(*in).DeepCopyInto(*out)
	}
	if in.HorizontalPodAutoscaler != nil {
		in, out := &in.HorizontalPodAutoscaler, &out.HorizontalPodAutoscaler
		*out = new(shared.KubernetesResourceOverlay)
		(*in).DeepCopyInto(*out)
	}
	if in.VerticalPodAutoscaler != nil {
		in, out := &in.VerticalPodAutoscaler, &out.VerticalPodAutoscaler
		*out = new(shared.KubernetesResourceOverlay)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionDeployment.
func (in *ExtensionDeployment) DeepCopy() *ExtensionDeployment {
	if in == nil {
		return nil
	}
	out := new(ExtensionDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenExchangeCfg) DeepCopyInto(out *TokenExchangeCfg) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(TokenExchangeMode)
		**out = **in
	}
	if in.Oidc != nil {
		in, out := &in.Oidc, &out.Oidc
		*out = new(TokenExchangeOidcConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenExchangeCfg.
func (in *TokenExchangeCfg) DeepCopy() *TokenExchangeCfg {
	if in == nil {
		return nil
	}
	out := new(TokenExchangeCfg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenExchangeOidcConfig) DeepCopyInto(out *TokenExchangeOidcConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenExchangeOidcConfig.
func (in *TokenExchangeOidcConfig) DeepCopy() *TokenExchangeOidcConfig {
	if in == nil {
		return nil
	}
	out := new(TokenExchangeOidcConfig)
	in.DeepCopyInto(out)
	return out
}
