/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package enterprisekgateway

import (
	context "context"

	v1alpha1enterprisekgateway "github.com/solo-io/kgateway-client/v2/api/v1alpha1/enterprisekgateway"
	scheme "github.com/solo-io/kgateway-client/v2/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EnterpriseKgatewayDestinationSelectorsGetter has a method to return a EnterpriseKgatewayDestinationSelectorInterface.
// A group's client should implement this interface.
type EnterpriseKgatewayDestinationSelectorsGetter interface {
	EnterpriseKgatewayDestinationSelectors(namespace string) EnterpriseKgatewayDestinationSelectorInterface
}

// EnterpriseKgatewayDestinationSelectorInterface has methods to work with EnterpriseKgatewayDestinationSelector resources.
type EnterpriseKgatewayDestinationSelectorInterface interface {
	Create(ctx context.Context, enterpriseKgatewayDestinationSelector *v1alpha1enterprisekgateway.EnterpriseKgatewayDestinationSelector, opts v1.CreateOptions) (*v1alpha1enterprisekgateway.EnterpriseKgatewayDestinationSelector, error)
	Update(ctx context.Context, enterpriseKgatewayDestinationSelector *v1alpha1enterprisekgateway.EnterpriseKgatewayDestinationSelector, opts v1.UpdateOptions) (*v1alpha1enterprisekgateway.EnterpriseKgatewayDestinationSelector, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, enterpriseKgatewayDestinationSelector *v1alpha1enterprisekgateway.EnterpriseKgatewayDestinationSelector, opts v1.UpdateOptions) (*v1alpha1enterprisekgateway.EnterpriseKgatewayDestinationSelector, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1enterprisekgateway.EnterpriseKgatewayDestinationSelector, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1enterprisekgateway.EnterpriseKgatewayDestinationSelectorList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1enterprisekgateway.EnterpriseKgatewayDestinationSelector, err error)
	EnterpriseKgatewayDestinationSelectorExpansion
}

// enterpriseKgatewayDestinationSelectors implements EnterpriseKgatewayDestinationSelectorInterface
type enterpriseKgatewayDestinationSelectors struct {
	*gentype.ClientWithList[*v1alpha1enterprisekgateway.EnterpriseKgatewayDestinationSelector, *v1alpha1enterprisekgateway.EnterpriseKgatewayDestinationSelectorList]
}

// newEnterpriseKgatewayDestinationSelectors returns a EnterpriseKgatewayDestinationSelectors
func newEnterpriseKgatewayDestinationSelectors(c *EnterprisekgatewayEnterprisekgatewayClient, namespace string) *enterpriseKgatewayDestinationSelectors {
	return &enterpriseKgatewayDestinationSelectors{
		gentype.NewClientWithList[*v1alpha1enterprisekgateway.EnterpriseKgatewayDestinationSelector, *v1alpha1enterprisekgateway.EnterpriseKgatewayDestinationSelectorList](
			"enterprisekgatewaydestinationselectors",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1enterprisekgateway.EnterpriseKgatewayDestinationSelector {
				return &v1alpha1enterprisekgateway.EnterpriseKgatewayDestinationSelector{}
			},
			func() *v1alpha1enterprisekgateway.EnterpriseKgatewayDestinationSelectorList {
				return &v1alpha1enterprisekgateway.EnterpriseKgatewayDestinationSelectorList{}
			},
		),
	}
}
