/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package enterprisekgateway

import (
	context "context"

	v1alpha1enterprisekgateway "github.com/solo-io/kgateway-client/api/v1alpha1/enterprisekgateway"
	scheme "github.com/solo-io/kgateway-client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EnterpriseKgatewayTrafficPoliciesGetter has a method to return a EnterpriseKgatewayTrafficPolicyInterface.
// A group's client should implement this interface.
type EnterpriseKgatewayTrafficPoliciesGetter interface {
	EnterpriseKgatewayTrafficPolicies(namespace string) EnterpriseKgatewayTrafficPolicyInterface
}

// EnterpriseKgatewayTrafficPolicyInterface has methods to work with EnterpriseKgatewayTrafficPolicy resources.
type EnterpriseKgatewayTrafficPolicyInterface interface {
	Create(ctx context.Context, enterpriseKgatewayTrafficPolicy *v1alpha1enterprisekgateway.EnterpriseKgatewayTrafficPolicy, opts v1.CreateOptions) (*v1alpha1enterprisekgateway.EnterpriseKgatewayTrafficPolicy, error)
	Update(ctx context.Context, enterpriseKgatewayTrafficPolicy *v1alpha1enterprisekgateway.EnterpriseKgatewayTrafficPolicy, opts v1.UpdateOptions) (*v1alpha1enterprisekgateway.EnterpriseKgatewayTrafficPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, enterpriseKgatewayTrafficPolicy *v1alpha1enterprisekgateway.EnterpriseKgatewayTrafficPolicy, opts v1.UpdateOptions) (*v1alpha1enterprisekgateway.EnterpriseKgatewayTrafficPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1enterprisekgateway.EnterpriseKgatewayTrafficPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1enterprisekgateway.EnterpriseKgatewayTrafficPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1enterprisekgateway.EnterpriseKgatewayTrafficPolicy, err error)
	EnterpriseKgatewayTrafficPolicyExpansion
}

// enterpriseKgatewayTrafficPolicies implements EnterpriseKgatewayTrafficPolicyInterface
type enterpriseKgatewayTrafficPolicies struct {
	*gentype.ClientWithList[*v1alpha1enterprisekgateway.EnterpriseKgatewayTrafficPolicy, *v1alpha1enterprisekgateway.EnterpriseKgatewayTrafficPolicyList]
}

// newEnterpriseKgatewayTrafficPolicies returns a EnterpriseKgatewayTrafficPolicies
func newEnterpriseKgatewayTrafficPolicies(c *EnterprisekgatewayEnterprisekgatewayClient, namespace string) *enterpriseKgatewayTrafficPolicies {
	return &enterpriseKgatewayTrafficPolicies{
		gentype.NewClientWithList[*v1alpha1enterprisekgateway.EnterpriseKgatewayTrafficPolicy, *v1alpha1enterprisekgateway.EnterpriseKgatewayTrafficPolicyList](
			"enterprisekgatewaytrafficpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1enterprisekgateway.EnterpriseKgatewayTrafficPolicy {
				return &v1alpha1enterprisekgateway.EnterpriseKgatewayTrafficPolicy{}
			},
			func() *v1alpha1enterprisekgateway.EnterpriseKgatewayTrafficPolicyList {
				return &v1alpha1enterprisekgateway.EnterpriseKgatewayTrafficPolicyList{}
			},
		),
	}
}
