/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package enterpriseagentgateway

import (
	context "context"

	v1alpha1enterpriseagentgateway "github.com/solo-io/kgateway-client/api/v1alpha1/enterpriseagentgateway"
	scheme "github.com/solo-io/kgateway-client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EnterpriseAgentgatewayPoliciesGetter has a method to return a EnterpriseAgentgatewayPolicyInterface.
// A group's client should implement this interface.
type EnterpriseAgentgatewayPoliciesGetter interface {
	EnterpriseAgentgatewayPolicies(namespace string) EnterpriseAgentgatewayPolicyInterface
}

// EnterpriseAgentgatewayPolicyInterface has methods to work with EnterpriseAgentgatewayPolicy resources.
type EnterpriseAgentgatewayPolicyInterface interface {
	Create(ctx context.Context, enterpriseAgentgatewayPolicy *v1alpha1enterpriseagentgateway.EnterpriseAgentgatewayPolicy, opts v1.CreateOptions) (*v1alpha1enterpriseagentgateway.EnterpriseAgentgatewayPolicy, error)
	Update(ctx context.Context, enterpriseAgentgatewayPolicy *v1alpha1enterpriseagentgateway.EnterpriseAgentgatewayPolicy, opts v1.UpdateOptions) (*v1alpha1enterpriseagentgateway.EnterpriseAgentgatewayPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, enterpriseAgentgatewayPolicy *v1alpha1enterpriseagentgateway.EnterpriseAgentgatewayPolicy, opts v1.UpdateOptions) (*v1alpha1enterpriseagentgateway.EnterpriseAgentgatewayPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1enterpriseagentgateway.EnterpriseAgentgatewayPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1enterpriseagentgateway.EnterpriseAgentgatewayPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1enterpriseagentgateway.EnterpriseAgentgatewayPolicy, err error)
	EnterpriseAgentgatewayPolicyExpansion
}

// enterpriseAgentgatewayPolicies implements EnterpriseAgentgatewayPolicyInterface
type enterpriseAgentgatewayPolicies struct {
	*gentype.ClientWithList[*v1alpha1enterpriseagentgateway.EnterpriseAgentgatewayPolicy, *v1alpha1enterpriseagentgateway.EnterpriseAgentgatewayPolicyList]
}

// newEnterpriseAgentgatewayPolicies returns a EnterpriseAgentgatewayPolicies
func newEnterpriseAgentgatewayPolicies(c *EnterprisekgatewayEnterpriseagentgatewayClient, namespace string) *enterpriseAgentgatewayPolicies {
	return &enterpriseAgentgatewayPolicies{
		gentype.NewClientWithList[*v1alpha1enterpriseagentgateway.EnterpriseAgentgatewayPolicy, *v1alpha1enterpriseagentgateway.EnterpriseAgentgatewayPolicyList](
			"enterpriseagentgatewaypolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1enterpriseagentgateway.EnterpriseAgentgatewayPolicy {
				return &v1alpha1enterpriseagentgateway.EnterpriseAgentgatewayPolicy{}
			},
			func() *v1alpha1enterpriseagentgateway.EnterpriseAgentgatewayPolicyList {
				return &v1alpha1enterpriseagentgateway.EnterpriseAgentgatewayPolicyList{}
			},
		),
	}
}
