/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package enterpriseagentgateway

import (
	http "net/http"

	v1alpha1enterpriseagentgateway "github.com/solo-io/kgateway-client/api/v1alpha1/enterpriseagentgateway"
	scheme "github.com/solo-io/kgateway-client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type EnterprisekgatewayEnterpriseagentgatewayInterface interface {
	RESTClient() rest.Interface
	EnterpriseAgentgatewayParametersGetter
	EnterpriseAgentgatewayPoliciesGetter
}

// EnterprisekgatewayEnterpriseagentgatewayClient is used to interact with features provided by the enterpriseagentgateway.solo.io group.
type EnterprisekgatewayEnterpriseagentgatewayClient struct {
	restClient rest.Interface
}

func (c *EnterprisekgatewayEnterpriseagentgatewayClient) EnterpriseAgentgatewayParameters(namespace string) EnterpriseAgentgatewayParametersInterface {
	return newEnterpriseAgentgatewayParameters(c, namespace)
}

func (c *EnterprisekgatewayEnterpriseagentgatewayClient) EnterpriseAgentgatewayPolicies(namespace string) EnterpriseAgentgatewayPolicyInterface {
	return newEnterpriseAgentgatewayPolicies(c, namespace)
}

// NewForConfig creates a new EnterprisekgatewayEnterpriseagentgatewayClient for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*EnterprisekgatewayEnterpriseagentgatewayClient, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new EnterprisekgatewayEnterpriseagentgatewayClient for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*EnterprisekgatewayEnterpriseagentgatewayClient, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &EnterprisekgatewayEnterpriseagentgatewayClient{client}, nil
}

// NewForConfigOrDie creates a new EnterprisekgatewayEnterpriseagentgatewayClient for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *EnterprisekgatewayEnterpriseagentgatewayClient {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new EnterprisekgatewayEnterpriseagentgatewayClient for the given RESTClient.
func New(c rest.Interface) *EnterprisekgatewayEnterpriseagentgatewayClient {
	return &EnterprisekgatewayEnterpriseagentgatewayClient{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := v1alpha1enterpriseagentgateway.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *EnterprisekgatewayEnterpriseagentgatewayClient) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
