/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clientset "github.com/solo-io/gloo-gateway/v2/internal/client/clientset/versioned"
	extauthv1 "github.com/solo-io/gloo-gateway/v2/internal/client/clientset/versioned/typed/extauth.solo.io/v1"
	fakeextauthv1 "github.com/solo-io/gloo-gateway/v2/internal/client/clientset/versioned/typed/extauth.solo.io/v1/fake"
	ratelimitv1alpha1 "github.com/solo-io/gloo-gateway/v2/internal/client/clientset/versioned/typed/ratelimit.solo.io/v1alpha1"
	fakeratelimitv1alpha1 "github.com/solo-io/gloo-gateway/v2/internal/client/clientset/versioned/typed/ratelimit.solo.io/v1alpha1/fake"
	enterprisekgatewayenterpriseagentgateway "github.com/solo-io/gloo-gateway/v2/internal/client/clientset/versioned/typed/v1alpha1/enterpriseagentgateway"
	fakeenterprisekgatewayenterpriseagentgateway "github.com/solo-io/gloo-gateway/v2/internal/client/clientset/versioned/typed/v1alpha1/enterpriseagentgateway/fake"
	enterprisekgatewayenterprisekgateway "github.com/solo-io/gloo-gateway/v2/internal/client/clientset/versioned/typed/v1alpha1/enterprisekgateway"
	fakeenterprisekgatewayenterprisekgateway "github.com/solo-io/gloo-gateway/v2/internal/client/clientset/versioned/typed/v1alpha1/enterprisekgateway/fake"
	enterprisekgatewayenterprisesolo "github.com/solo-io/gloo-gateway/v2/internal/client/clientset/versioned/typed/v1alpha1/enterprisesolo"
	fakeenterprisekgatewayenterprisesolo "github.com/solo-io/gloo-gateway/v2/internal/client/clientset/versioned/typed/v1alpha1/enterprisesolo/fake"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/discovery"
	fakediscovery "k8s.io/client-go/discovery/fake"
	"k8s.io/client-go/testing"
)

// NewSimpleClientset returns a clientset that will respond with the provided objects.
// It's backed by a very simple object tracker that processes creates, updates and deletions as-is,
// without applying any field management, validations and/or defaults. It shouldn't be considered a replacement
// for a real clientset and is mostly useful in simple unit tests.
//
// DEPRECATED: NewClientset replaces this with support for field management, which significantly improves
// server side apply testing. NewClientset is only available when apply configurations are generated (e.g.
// via --with-applyconfig).
func NewSimpleClientset(objects ...runtime.Object) *Clientset {
	o := testing.NewObjectTracker(scheme, codecs.UniversalDecoder())
	for _, obj := range objects {
		if err := o.Add(obj); err != nil {
			panic(err)
		}
	}

	cs := &Clientset{tracker: o}
	cs.discovery = &fakediscovery.FakeDiscovery{Fake: &cs.Fake}
	cs.AddReactor("*", "*", testing.ObjectReaction(o))
	cs.AddWatchReactor("*", func(action testing.Action) (handled bool, ret watch.Interface, err error) {
		var opts metav1.ListOptions
		if watchActcion, ok := action.(testing.WatchActionImpl); ok {
			opts = watchActcion.ListOptions
		}
		gvr := action.GetResource()
		ns := action.GetNamespace()
		watch, err := o.Watch(gvr, ns, opts)
		if err != nil {
			return false, nil, err
		}
		return true, watch, nil
	})

	return cs
}

// Clientset implements clientset.Interface. Meant to be embedded into a
// struct to get a default implementation. This makes faking out just the method
// you want to test easier.
type Clientset struct {
	testing.Fake
	discovery *fakediscovery.FakeDiscovery
	tracker   testing.ObjectTracker
}

func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	return c.discovery
}

func (c *Clientset) Tracker() testing.ObjectTracker {
	return c.tracker
}

var (
	_ clientset.Interface = &Clientset{}
	_ testing.FakeClient  = &Clientset{}
)

// ExtauthV1 retrieves the ExtauthV1Client
func (c *Clientset) ExtauthV1() extauthv1.ExtauthV1Interface {
	return &fakeextauthv1.FakeExtauthV1{Fake: &c.Fake}
}

// RatelimitV1alpha1 retrieves the RatelimitV1alpha1Client
func (c *Clientset) RatelimitV1alpha1() ratelimitv1alpha1.RatelimitV1alpha1Interface {
	return &fakeratelimitv1alpha1.FakeRatelimitV1alpha1{Fake: &c.Fake}
}

// EnterprisekgatewayEnterprisekgateway retrieves the EnterprisekgatewayEnterprisekgatewayClient
func (c *Clientset) EnterprisekgatewayEnterprisekgateway() enterprisekgatewayenterprisekgateway.EnterprisekgatewayEnterprisekgatewayInterface {
	return &fakeenterprisekgatewayenterprisekgateway.FakeEnterprisekgatewayEnterprisekgateway{Fake: &c.Fake}
}

// EnterprisekgatewayEnterpriseagentgateway retrieves the EnterprisekgatewayEnterpriseagentgatewayClient
func (c *Clientset) EnterprisekgatewayEnterpriseagentgateway() enterprisekgatewayenterpriseagentgateway.EnterprisekgatewayEnterpriseagentgatewayInterface {
	return &fakeenterprisekgatewayenterpriseagentgateway.FakeEnterprisekgatewayEnterpriseagentgateway{Fake: &c.Fake}
}

// EnterprisekgatewayEnterprisesolo retrieves the EnterprisekgatewayEnterprisesoloClient
func (c *Clientset) EnterprisekgatewayEnterprisesolo() enterprisekgatewayenterprisesolo.EnterprisekgatewayEnterprisesoloInterface {
	return &fakeenterprisekgatewayenterprisesolo.FakeEnterprisekgatewayEnterprisesolo{Fake: &c.Fake}
}
