package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:rbac:groups=portal.solo.io,resources=portalconfigs,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=portal.solo.io,resources=portalconfigs/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=enterprisekgateway.solo.io,resources=enterprisekgatewaytrafficpolicies,verbs=get;list;watch

// PortalConfig is the intermediate representation for a Portal's API catalog.
// Generated by the Portal Controller, consumed by the Portal Web Server.
//
// +genclient
// +kubebuilder:object:root=true
// +kubebuilder:resource:categories={gloo,portal},path=portalconfigs,shortName=pc
// +kubebuilder:metadata:labels={app=gloo,app.kubernetes.io/name=portalconfig}
type PortalConfig struct {
	metav1.TypeMeta `json:",inline"`
	// +optional
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// spec defines the API catalog for this portal
	// +required
	Spec PortalConfigSpec `json:"spec"`
}

// PortalConfigSpec defines the desired state of PortalConfig
type PortalConfigSpec struct {
	// apis is the list of API products/versions visible in this portal
	// +listType=atomic
	// +optional
	APIs []PortalAPI `json:"apis,omitempty"`

	// portalMetadata contains portal-level configuration
	// +required
	PortalMetadata PortalMetadata `json:"portalMetadata"`

	// visibility controls the access requirements for viewing the portal's API catalog.
	// +optional
	Visibility *PortalConfigVisibility `json:"visibility,omitempty"`
}

// PortalConfigVisibility is the internal representation of PortalVisibility consumed by the portal web backend.
type PortalConfigVisibility struct {
	// public controls whether the portal's API catalog is publicly accessible without authentication.
	// +optional
	Public *bool `json:"public,omitempty"`
}

// PortalMetadata contains portal branding and configuration
type PortalMetadata struct {
	// name is the portal's display name
	// +kubebuilder:validation:MinLength=1
	// +required
	Name string `json:"name"`
}

// PortalAPI represents an API product version in the portal
type PortalAPI struct {
	// apiProductId is the unique identifier for the API product
	// +kubebuilder:validation:MinLength=1
	// +required
	APIProductID string `json:"apiProductId"`

	// apiProductDisplayName is the display name for the API product
	// +required
	APIProductDisplayName string `json:"apiProductDisplayName"`

	// apiProductDescription is the product-level description from ApiProduct.spec.description
	// +optional
	APIProductDescription *string `json:"apiProductDescription,omitempty"`

	// apiVersion is the version string (e.g., "v1", "v2")
	// +kubebuilder:validation:MinLength=1
	// +required
	APIVersion string `json:"apiVersion"`

	// title from OpenAPI metadata
	// +optional
	Title *string `json:"title,omitempty"`

	// description from OpenAPI metadata
	// +optional
	Description *string `json:"description,omitempty"`

	// termsOfService from OpenAPI metadata
	// +optional
	TermsOfService *string `json:"termsOfService,omitempty"`

	// contact is the product-level contact email from ApiProduct.spec.contactEmail.
	// Despite the generic field name, this carries the product contactEmail (not the
	// version's OpenAPI contact, which feeds the stitched spec's info.contact separately).
	// +optional
	Contact *string `json:"contact,omitempty"`

	// license from OpenAPI metadata
	// +optional
	License *string `json:"license,omitempty"`

	// apiProductCustomMetadata from ApiProduct.spec.customMetadata
	// +optional
	APIProductCustomMetadata map[string]string `json:"apiProductCustomMetadata,omitempty"`

	// apiVersionCustomMetadata from ApiProduct.spec.versions[].customMetadata
	// +optional
	APIVersionCustomMetadata map[string]string `json:"apiVersionCustomMetadata,omitempty"`

	// apiDocRef references the ApiDoc containing the OpenAPI spec.
	// Web server fetches the spec from ApiDoc on-demand to avoid etcd size limits.
	// +optional
	ApiDocRef *ApiDocReference `json:"apiDocRef,omitempty"`

	// visibility is the visibility configuration for the API.
	// When nil, no gating applies for this API beyond the Portal level public flag.
	// +optional
	Visibility *PortalAPIVisibility `json:"visibility,omitempty"`
}

// AuthType indicates the type of authentication required.
type AuthType string

const (
	// AuthTypeExtAuth indicates external authentication via AuthConfig.
	AuthTypeExtAuth AuthType = "extauth"
)

// ApiDocReference references an ApiDoc resource.
// Used in PortalConfig to point the web server to the ApiDoc containing the OpenAPI spec.
type ApiDocReference struct {
	// name of the ApiDoc.
	// +kubebuilder:validation:MinLength=1
	// +required
	Name string `json:"name"`

	// namespace of the ApiDoc.
	// +kubebuilder:validation:MinLength=1
	// +required
	Namespace string `json:"namespace"`
}

// PortalConfigList contains a list of PortalConfig resources
// +kubebuilder:object:root=true
type PortalConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PortalConfig `json:"items"`
}

// PortalAPIVisibility is the per-API access requirement consumed by the portal web backend.
type PortalAPIVisibility struct {
	// membership is the deduped union of claim groups contributed by all
	// VisibilityPolicy memberships that apply to this API (per-product + portal-wide).
	// OR across groups; AND within a group.
	// +listType=atomic
	// +optional
	Membership []ClaimGroup `json:"membership,omitempty"`

	// allRefsUnresolved indicates that VisibilityPolicy references were declared
	// for this API but none could be resolved. The backend treats the API as
	// hidden from non-admin callers when set to true.
	// +optional
	AllRefsUnresolved bool `json:"allRefsUnresolved,omitempty"`
}
