/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package enterprisesolo

import (
	context "context"

	v1alpha1enterprisesolo "github.com/solo-io/kgateway-client/v2/api/v1alpha1/enterprisesolo"
	scheme "github.com/solo-io/kgateway-client/v2/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// EnterpriseListenerSetsGetter has a method to return a EnterpriseListenerSetInterface.
// A group's client should implement this interface.
type EnterpriseListenerSetsGetter interface {
	EnterpriseListenerSets(namespace string) EnterpriseListenerSetInterface
}

// EnterpriseListenerSetInterface has methods to work with EnterpriseListenerSet resources.
type EnterpriseListenerSetInterface interface {
	Create(ctx context.Context, enterpriseListenerSet *v1alpha1enterprisesolo.EnterpriseListenerSet, opts v1.CreateOptions) (*v1alpha1enterprisesolo.EnterpriseListenerSet, error)
	Update(ctx context.Context, enterpriseListenerSet *v1alpha1enterprisesolo.EnterpriseListenerSet, opts v1.UpdateOptions) (*v1alpha1enterprisesolo.EnterpriseListenerSet, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, enterpriseListenerSet *v1alpha1enterprisesolo.EnterpriseListenerSet, opts v1.UpdateOptions) (*v1alpha1enterprisesolo.EnterpriseListenerSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1enterprisesolo.EnterpriseListenerSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1enterprisesolo.EnterpriseListenerSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1enterprisesolo.EnterpriseListenerSet, err error)
	EnterpriseListenerSetExpansion
}

// enterpriseListenerSets implements EnterpriseListenerSetInterface
type enterpriseListenerSets struct {
	*gentype.ClientWithList[*v1alpha1enterprisesolo.EnterpriseListenerSet, *v1alpha1enterprisesolo.EnterpriseListenerSetList]
}

// newEnterpriseListenerSets returns a EnterpriseListenerSets
func newEnterpriseListenerSets(c *EnterprisekgatewayEnterprisesoloClient, namespace string) *enterpriseListenerSets {
	return &enterpriseListenerSets{
		gentype.NewClientWithList[*v1alpha1enterprisesolo.EnterpriseListenerSet, *v1alpha1enterprisesolo.EnterpriseListenerSetList](
			"enterpriselistenersets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1enterprisesolo.EnterpriseListenerSet {
				return &v1alpha1enterprisesolo.EnterpriseListenerSet{}
			},
			func() *v1alpha1enterprisesolo.EnterpriseListenerSetList {
				return &v1alpha1enterprisesolo.EnterpriseListenerSetList{}
			},
		),
	}
}
